# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Oberfl_main.ui'
#
# Created: Fri Feb 20 00:26:37 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 708)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frakOptDockWidget = QtGui.QDockWidget(self.centralwidget)
        self.frakOptDockWidget.setMaximumSize(QtCore.QSize(301, 524287))
        self.frakOptDockWidget.setObjectName("frakOptDockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tiefeLabel = QtGui.QLabel(self.dockWidgetContents)
        self.tiefeLabel.setObjectName("tiefeLabel")
        self.horizontalLayout.addWidget(self.tiefeLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.TiefeSpinBox = QtGui.QSpinBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TiefeSpinBox.sizePolicy().hasHeightForWidth())
        self.TiefeSpinBox.setSizePolicy(sizePolicy)
        self.TiefeSpinBox.setMaximum(10000000)
        self.TiefeSpinBox.setObjectName("TiefeSpinBox")
        self.horizontalLayout.addWidget(self.TiefeSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.zoomRechtsLabel = QtGui.QLabel(self.dockWidgetContents)
        self.zoomRechtsLabel.setObjectName("zoomRechtsLabel")
        self.horizontalLayout_3.addWidget(self.zoomRechtsLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.zoomLinksLabel = QtGui.QLabel(self.dockWidgetContents)
        self.zoomLinksLabel.setObjectName("zoomLinksLabel")
        self.horizontalLayout_2.addWidget(self.zoomLinksLabel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.zoomRechtsLineEdit = QtGui.QLineEdit(self.dockWidgetContents)
        self.zoomRechtsLineEdit.setObjectName("zoomRechtsLineEdit")
        self.gridLayout.addWidget(self.zoomRechtsLineEdit, 0, 1, 1, 1)
        self.zoomLinksLineEdit = QtGui.QLineEdit(self.dockWidgetContents)
        self.zoomLinksLineEdit.setObjectName("zoomLinksLineEdit")
        self.gridLayout.addWidget(self.zoomLinksLineEdit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 440, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.frakOptDockWidget.setWidget(self.dockWidgetContents)
        self.horizontalLayout_4.addWidget(self.frakOptDockWidget)
        self.FraktalBildWidget = Fraktal_Bild(self.centralwidget)
        self.FraktalBildWidget.setMinimumSize(QtCore.QSize(521, 0))
        self.FraktalBildWidget.setObjectName("FraktalBildWidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.FraktalBildWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem4 = QtGui.QSpacerItem(700, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.FraktalBildWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 25))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtGui.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFraktal_oeffnen = QtGui.QAction(MainWindow)
        self.actionFraktal_oeffnen.setObjectName("actionFraktal_oeffnen")
        self.actionBild_speichern = QtGui.QAction(MainWindow)
        self.actionBild_speichern.setObjectName("actionBild_speichern")
        self.actionBeenden = QtGui.QAction(MainWindow)
        self.actionBeenden.setObjectName("actionBeenden")
        self.actionZeichne = QtGui.QAction(MainWindow)
        self.actionZeichne.setObjectName("actionZeichne")
        self.actionZoom = QtGui.QAction(MainWindow)
        self.actionZoom.setObjectName("actionZoom")
        self.menuDatei.addAction(self.actionFraktal_oeffnen)
        self.menuDatei.addAction(self.actionBild_speichern)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionBeenden)
        self.menubar.addAction(self.menuDatei.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tiefeLabel.setText(QtGui.QApplication.translate("MainWindow", "Zu zeichnende Tiefe:", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomRechtsLabel.setText(QtGui.QApplication.translate("MainWindow", "Obere rechte Ecke:", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomLinksLabel.setText(QtGui.QApplication.translate("MainWindow", "Untere linke Ecke:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatei.setTitle(QtGui.QApplication.translate("MainWindow", "Datei", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFraktal_oeffnen.setText(QtGui.QApplication.translate("MainWindow", "Fraktal öffnen...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBild_speichern.setText(QtGui.QApplication.translate("MainWindow", "Bild speichern", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBeenden.setText(QtGui.QApplication.translate("MainWindow", "Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZeichne.setText(QtGui.QApplication.translate("MainWindow", "zeichne", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoom.setText(QtGui.QApplication.translate("MainWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))

from Graphische_Oberfl import Fraktal_Bild
